title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-s25/team02-s25-02
owner: ucsb-cs156-s25
repo_name: team02-s25-02
pull_requests: [{"author":{"id":"U_kgDOB3DYsg","is_bot":false,"login":"evaniacheng","name":"evania"},"headRefName":"ec-e2e","number":109,"title":"ec - End to End Test for RecommendationRequest","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/109"},{"author":{"id":"U_kgDOCNoKew","is_bot":false,"login":"AyalaWang","name":""},"headRefName":"aw-helpRequest-Table","number":101,"title":"Aw help request table","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/101"},{"author":{"id":"U_kgDOCNoKew","is_bot":false,"login":"AyalaWang","name":""},"headRefName":"aw-helpRequest-form","number":100,"title":"Aw help request form","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/100"},{"author":{"id":"MDQ6VXNlcjU5OTg4MTUw","is_bot":false,"login":"andrew200356","name":"Andrew Wang"},"headRefName":"sw-MenuItemReview","number":97,"title":"Sw MenuItemReview Table and Form","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/97"}]
