
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-02
owner: ucsb-cs156-s25
repo_name: team02-s25-02
pull_requests: [{"author":{"id":"U_kgDOBXvSwA","is_bot":false,"login":"jiahuaren","name":"Jiahua Ren"},"headRefName":"jr-UCSBOrgs-fixtures","number":65,"title":"jr - adding UCSB Organization Fixtures","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/65"},{"author":{"id":"U_kgDOBXvSwA","is_bot":false,"login":"jiahuaren","name":"Jiahua Ren"},"headRefName":"jr-UCSBOrganization-backend","number":64,"title":"jr - Add backend for CRUD operations for UCSBOrganizations","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/64"},{"author":{"id":"U_kgDOB3DYsg","is_bot":false,"login":"evaniacheng","name":"evania"},"headRefName":"ec-crudapi-files","number":62,"title":"ec - Copy files for Backend CRUD API RecommendationRequest from team01","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/62"},{"author":{"id":"U_kgDOB3DYsg","is_bot":false,"login":"evaniacheng","name":"evania"},"headRefName":"ec-recommendationRequestFixtures","number":61,"title":"ec - createdFixtures for RecommendationRequest","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/61"}]
