title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-s25/team02-s25-02
owner: ucsb-cs156-s25
repo_name: team02-s25-02
pull_requests: [{"author":{"id":"U_kgDOB3DYsg","is_bot":false,"login":"evaniacheng","name":"evania"},"headRefName":"ec-edit","number":96,"title":"ec - Edit Page for RecommendationRequest plus tests and stories","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/96"},{"author":{"id":"U_kgDOB3DYsg","is_bot":false,"login":"evaniacheng","name":"evania"},"headRefName":"ec-create","number":94,"title":"ec - Create Page for RecommendationRequest plus tests and stories","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/94"},{"author":{"id":"U_kgDOB3DYsg","is_bot":false,"login":"evaniacheng","name":"evania"},"headRefName":"ec-index","number":93,"title":"ec - Index Page for RecommendationRequest plus tests and stories","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/93"},{"author":{"id":"U_kgDOB3DYsg","is_bot":false,"login":"evaniacheng","name":"evania"},"headRefName":"ec-placeholder","number":92,"title":"ec - Copy Placeholders for RecommendationRequest pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/92"},{"author":{"id":"U_kgDOBtgnsg","is_bot":false,"login":"mujiaaa","name":"Mujia Chen"},"headRefName":"mc-article-index-page","number":91,"title":"Mc - article index page","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/91"}]
