
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-02
owner: ucsb-cs156-s25
repo_name: team02-s25-02
pull_requests: [{"author":{"id":"U_kgDOCNoKew","is_bot":false,"login":"AyalaWang","name":""},"headRefName":"aw-HelpRequest-fixtures","number":80,"title":"aw - fix frontend code formatting","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/80"},{"author":{"id":"U_kgDOBtgnsg","is_bot":false,"login":"mujiaaa","name":"Mujia Chen"},"headRefName":"mc-article-fixtures","number":79,"title":"Mc - add form for articles","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/79"},{"author":{"id":"U_kgDOBXvSwA","is_bot":false,"login":"jiahuaren","name":"Jiahua Ren"},"headRefName":"jr-UCSBOrgs-edit","number":78,"title":"jr - create UCSB Orgs Edit page","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/78"},{"author":{"id":"U_kgDOBdVC1w","is_bot":false,"login":"Elskin","name":"Xinyan Zhao"},"headRefName":"xz-formcomponent","number":77,"title":"Xz formcomponent","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/77"},{"author":{"id":"U_kgDOBdVC1w","is_bot":false,"login":"Elskin","name":"Xinyan Zhao"},"headRefName":"xz-fixtures","number":76,"title":"Xz fixtures","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/76"},{"author":{"id":"U_kgDOBXvSwA","is_bot":false,"login":"jiahuaren","name":"Jiahua Ren"},"headRefName":"jr-UCSBOrgs-Index","number":74,"title":"jr - create UCSB Org Index Page","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/74"},{"author":{"id":"U_kgDOBXvSwA","is_bot":false,"login":"jiahuaren","name":"Jiahua Ren"},"headRefName":"jr-UCSBOrgs-create","number":73,"title":"jr - create UCSB Orgs Create Page","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/73"},{"author":{"id":"U_kgDOBXvSwA","is_bot":false,"login":"jiahuaren","name":"Jiahua Ren"},"headRefName":"jr-ucsbOrgs-placeholders","number":72,"title":"jr - copy placeholder files to UCSB Organization pages","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/72"},{"author":{"id":"U_kgDOBXvSwA","is_bot":false,"login":"jiahuaren","name":"Jiahua Ren"},"headRefName":"jr-UCSBOrgs-tablecomp","number":71,"title":"jr - create Table component and tests ","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/71"},{"author":{"id":"U_kgDOBXvSwA","is_bot":false,"login":"jiahuaren","name":"Jiahua Ren"},"headRefName":"jr-UCSBOrgs-formcomponent","number":70,"title":"jr - create Form component and tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/70"}]
