
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-02
owner: ucsb-cs156-s25
repo_name: team02-s25-02
pull_requests: [{"author":{"id":"U_kgDOBXvSwA","is_bot":false,"login":"jiahuaren","name":"Jiahua Ren"},"headRefName":"jr-UCSBOrgs-create","number":73,"title":"jr - create UCSB Orgs Create Page","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/73"},{"author":{"id":"U_kgDOBXvSwA","is_bot":false,"login":"jiahuaren","name":"Jiahua Ren"},"headRefName":"jr-ucsbOrgs-placeholders","number":72,"title":"jr - copy placeholder files to UCSB Organization pages","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/72"},{"author":{"id":"U_kgDOBXvSwA","is_bot":false,"login":"jiahuaren","name":"Jiahua Ren"},"headRefName":"jr-UCSBOrgs-tablecomp","number":71,"title":"jr - create Table component and tests ","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/71"},{"author":{"id":"U_kgDOBXvSwA","is_bot":false,"login":"jiahuaren","name":"Jiahua Ren"},"headRefName":"jr-UCSBOrgs-formcomponent","number":70,"title":"jr - create Form component and tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/70"},{"author":{"id":"U_kgDOBtgnsg","is_bot":false,"login":"mujiaaa","name":"Mujia Chen"},"headRefName":"mc-article-fixtures","number":69,"title":"mc - create fixtures for article table","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/69"},{"author":{"id":"U_kgDOBtgnsg","is_bot":false,"login":"mujiaaa","name":"Mujia Chen"},"headRefName":"mc-Articles-backend","number":68,"title":"mc - copy backend CRUD operations from team01 for the articles table","url":"https://github.com/ucsb-cs156-s25/team02-s25-02/pull/68"}]
